2-created_at: add field to db, sort comments, change add comment
lightalloy/days-of-code-bot pull request #11
Opened 2019-04-28 18:04 UTC by indra-uolles

2019-04-29 14:40 UTC, lightalloy commented on lib/repositories/challenge_comment_repo.rb
> +    challenge_comments.recent.ordered_by_created_at.limit(20).to_a
I think we should move ordering into the `recent` method. (My initial implementation looks underdone). `ordered_by_date` can be removed if it's not used.

2019-04-30 06:47 UTC, lightalloy approved these changes

2019-04-30 13:26 UTC, lightalloy requested changes
The default `created_at` value should be `null` (the simplest case, as discussed)

2019-06-17 19:46 UTC, indra-uolles commented
Tried the solution [here](https://stackoverflow.com/questions/46986793/default-now-in-sequel-generates-literal-embedded-into-the-defenitiion-of-a/51187823#51187823),

Everything looks fine to me, this is how new db looks after running seeds.rb:
![after_seeds_rb](https://user-images.githubusercontent.com/5262720/59631771-5242d180-9151-11e9-8a4e-4d5700a35754.jpg)
This is how /recent looks after I added comment:
![after_comment](https://user-images.githubusercontent.com/5262720/59631855-8d450500-9151-11e9-9b96-bcfc60540a83.jpg)

2019-06-18 15:34 UTC, lightalloy approved these changes

2019-06-18 15:34 UTC, merged